### ISSUE TITLE
页面错位

### ISSUE THREAD

**Issue by shixxz** [lwp2333/vite2-vue3-admin#1]
![image](https://user-images.githubusercontent.com/34824392/122697928-e3853b00-d278-11eb-9fab-70cc60e96309.png)
![image](https://user-images.githubusercontent.com/34824392/122697954-f1d35700-d278-11eb-9669-d19f8506a0c4.png)
你好，我已经star了，
我这边碰到两个问题，请帮忙看一下
1、菜单栏正常的，右侧的内容页错位了
2、Warning: [@ant-design/icons-vue] Make sure that you provide correct `viewBox` prop (default `0 0 1024 1024`) to the icon.
我没有找到这个问题在哪里
请帮忙处理一下

**Comment by lwp2333** [comment]
你好：
第一个问题：提供一下antd 版本 和浏览器环境，页面的布局是antd 自带的布局，可能和antd 版本有关
第二个问题：是因为ant design 2.x把图标 从antd 分离成一个单独的库了，而且每个图标都是一个命名组件，这样 开发不太好用，我把ant icon  重新封装了一次，然后全部注册了一遍（见 main.js  和component/aIcon），但图标是正常展示的，不影响

**Comment by shixxz** [comment]
第一个我已经找到问题了，是antd的版本有问题，需要升级到"ant-design-vue": "^2.2.0-beta",升级就没问题了

**Comment by yuanfangCBC** [comment]
相同遇到了这个。。
我给type了一个默认值就好。
![image](https://user-images.githubusercontent.com/11530689/134278428-f3f7116d-4202-4977-aeb8-010bb79a6ad2.png)

**Comment by lwp2333** [comment]
> 相同遇到了这个。。
> 我给type了一个默认值就好。
> ![image](https://user-images.githubusercontent.com/11530689/134278428-f3f7116d-4202-4977-aeb8-010bb79a6ad2.png)

**Comment by lwp2333** [comment]
> 相同遇到了这个。。
> 我给type了一个默认值就好。
> ![image](https://user-images.githubusercontent.com/11530689/134278428-f3f7116d-4202-4977-aeb8-010bb79a6ad2.png)

我已经改掉了这个问题，因为ant-design icon 必须有初始type，然后，菜单项全都是异步拿的数据，所以icon type 会从 null 变成 有 ant design icon 就会报错，我代码里面已经 更改过了，默认为 夹子姐（小风车~~~）

**Comment by lwp2333** [comment]
大家拉最新的代码哦，我最近打算重构成 typescript的，有兴趣的联系我一起玩啊哈哈哈~~~

**Comment by lwp2333** [comment]
update ant-design-vue version

**Comment by lwp2333** [comment]
update ant-design-vue version
