### ISSUE TITLE
注册之后无法登录

### ISSUE THREAD

**Issue by ZerTwo** [lwp2333/vite2-vue3-admin#2]
请问有账号密码吗

**Comment by lwp2333** [comment]
额😂，抱歉，注册无法登录的话，可能你注册的账号密码，和别人重复了，哈哈哈哈哈哈哈
当时写后端的时候，没写用户名唯一的校验，你可以试一下，想个奇奇怪怪一点的用户名和密码，哈哈哈
用户名：奇奇怪怪的用户， 密码：qiguai123，刚注册的😘

**Comment by ZerTwo** [comment]
多谢多谢，可以登录了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月28日(星期二) 下午5:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lwp2333/vite2-vue3-admin] 注册之后无法登录 (#2)





 
额😂，抱歉，注册无法登录的话，可能你注册的账号密码，和别人重复了，哈哈哈哈哈哈哈
 当时写后端的时候，没写用户名唯一的校验，你可以试一下，想个奇奇怪怪一点的用户名和密码，哈哈哈
 用户名：奇奇怪怪的用户， 密码：qiguai123，刚注册的😘
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lwp2333** [comment]
close issue
